### ISSUE TITLE
Library links is not working

### ISSUE THREAD

**Issue by worldwidemv** [worldwidemv/SimulinkBlock_RehaMove3#7]
[zahrabassiri](https://github.com/zahrabassiri) wrote in #1:

> hello,
> May I ask please to update the link for the library for Science Mode 3 (smpt_rm3_V3.2.4a)? the link that is provided in the instruction does not work.
> the main libraries that are needed for moving with the installation forward are:
> smpt_rm3_gcc_linux_x86_amd64_static
> incRehaMove_LibV3.2_lin_x86_64
>
> Although the library is in the section https://github.com/worldwidemv/SimulinkBlock_RehaMove3/issues/4 of the repository; however, it does not include incRehaMove_LibV3.2_lin_x86_64.
>
> Thanks.

**Comment by worldwidemv** [comment]
The library is from the HASOMED Company, which sold the stimulator.  
Since the stimulator is no longer sold, I guess the library was also removed.

I can send you my last version, if that helps.  
Otherwise, please contact HASOMED directly.

**Comment by zahrabassiri** [comment]
I will be appreciated if you can send me your version.

**Comment by worldwidemv** [comment]
where to?

**Comment by zahrabassiri** [comment]
Zahrabassiri@gmail.com

Thanks!

**Comment by zahrabassiri** [comment]
Hi,
May I have the file please. I will be appreciated if you please send it to
me.

**Comment by HolgerNahrstaedt** [comment]
You can download smpt_rm3_V3.2.4b.zip at the new location:
https://github.com/ScienceMode/ScienceMode3/blob/main/04_C%20Library_/smpt_rm3_V3.2.4b.zip

smpt_rm3_V3.2.4b.zip has a smpt_rm3_gcc_linux_x86_amd64_static directory with a precompiled library and should work.

**Comment by zahrabassiri** [comment]
It doesn’t work. Because it is missing
incRehaMove_LibV3.2_lin_x86_64


Please share this library if you have it.

**Comment by HolgerNahrstaedt** [comment]
incRehaMove_LibV3.2_lin_x86_64 is a copy of smpt_rm3_gcc_linux_x86_amd64_static 

https://github.com/worldwidemv/SimulinkBlock_RehaMove3/blob/08abd68a8af98d691f967e0ad6a90e2dcafa9db1/install_LIB_RehaMove3.m#L16

**Comment by zahrabassiri** [comment]
I afraid it is not. Because the following lines of code in  Install SRT
Blocks - RehaMove  script checks for both of these files snd stops the
installation process as it does not find
incRehaMove_LibV3.2_lin_x86_64.

addpath(fullfile(pwd, 'scripts', 'getRehaMoveLib')); if
(~isSmptLibAvailable( 'smpt_rm3_gcc_linux_x86_amd64_static',
'incRehaMove_LibV3.2_lin_x86_64' )) warning('The Hasomed SMPT library for
Linux 64 bit was not installed correctly!'); end

**Comment by zahrabassiri** [comment]
The lines of the script checks if it can find
incRehaMove_LibV3.2_lin_x86_64 inside
smpt_rm3_gcc_linux_x86_amd64_static and since it doesn’t find it, it gives
this error:

Warning: The Hasomed SMPT library for Linux 64 bit was not installed
correctly!

**Comment by HolgerNahrstaedt** [comment]
You can see here:
https://github.com/worldwidemv/SimulinkBlock_RehaMove3/blob/08abd68a8af98d691f967e0ad6a90e2dcafa9db1/scripts/getRehaMoveLib/copySmptLib.m#L45C5-L45C85

The content of smpt_rm3_gcc_linux_x86_amd64_static is copied to incRehaMove_LibV3.2_lin_x86_64.

You can do it also manually.
Just copy smpt_rm3_gcc_linux_x86_amd64_static to the git dir of SimulinkBlock_RehaMove3 and rename it manually to incRehaMove_LibV3.2_lin_x86_64

**Comment by worldwidemv** [comment]
Regarding the Library: check our Spam folder, however, the version Holgar shared is newer than the one I send you.

Regarding the Installation:  
* please check the [README.md](https://github.com/worldwidemv/SimulinkBlock_RehaMove3/blob/master/README.md) again and redo the install script [install_LIB_RehaMove3.m](https://github.com/worldwidemv/SimulinkBlock_RehaMove3/blob/master/install_LIB_RehaMove3.m)
* this script is coping the static linked library to the correct place
* only Linux is supported by the script

**Comment by zahrabassiri** [comment]
Hi,
You mean that I can’t install it in windows?

**Comment by zahrabassiri** [comment]
Thank you but there is nothing in my spam folder. My email address is
***@***.***

**Comment by worldwidemv** [comment]
> Hi, You mean that I can’t install it in windows?

Yes, Linux only.
As stated in the README.md, this block is intended for the [Soft-Realtime Toolchain (Matlab 2016b or so)](https://github.com/worldwidemv/SimulinkToolchain), which is only available for Linux. There was also a MAC port, but  this was never officially supported.

The build script [(build_LIB_RehaMove3.m)](https://github.com/worldwidemv/SimulinkBlock_RehaMove3/blob/master/build_LIB_RehaMove3.m) relies on this toolchain, however you can probably change/rewrite it, to work on Windows.

I am not sure if the block itself is platform specific, maybe POSIX, so maybe you can rewrite some stuff to fit your needs.
 
Anyway, I think there is also Python based interface available on [Github...](https://github.com/search?q=rehamove&type=repositories)

**Comment by zahrabassiri** [comment]
But I have seen people using it in windows. Unfortunately he left our
department and is not responsive anymore.
